
server:
    port: 1200

    servlet:
        context-path: /sms
spring:
    application:
        name: sms

    datasource:
        url: jdbc:mysql://localhost/sms
        username: root
        password: root

    jpa:
        hibernate:
            ddl-auto: update

        show-sql: true

        properties:
            hibernate:
                format_sql: true